name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Push Docker image to ECR
        run: |
          docker tag myapp:latest 147360193006.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          docker push 147360193006.dkr.ecr.us-east-1.amazonaws.com/myapp:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.204.228.199 "sudo yum update -y && sudo yum install -y docker && sudo service docker start && docker pull 147360193006.dkr.ecr.us-east-1.amazonaws.com/myapp:latest && docker run -d -p 80:80 147360193006.dkr.ecr.us-east-1.amazonaws.com/myapp:latest"
